# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build master

on:
  push:
    branches: [ master ]
env:
  IMAGE_TAG: sha-${{ github.sha }}
  GIT_REPO_NAME: 'mortage-app'
  PROJECT_NAME: mypublicproject
  REPO_NAME_APP: mortage-app
  KAAS_DEPLOYMENT_APP: mortage-app--deployment
  JAVA_VERSION: 11
  MAVEN_VERSION: 3.5.4

jobs:
  build:
    runs-on: [ ubuntu-latest, kaas, Linux ]

    steps:
    - name : Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Login in Docker hub
      uses: docker/login-action@v1
      with:
          registry: https://hub.docker.com/
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

